"""
Mini-game content pools for the Solace economy drop system.

Pool sizes:
  Trivia:       300 questions
  Scramble:      50 words
  Emoji:         50 puzzles
  Fill-blank:    50 prompts
  Fast math:     50 equations
  True/False:    50 statements
"""

from __future__ import annotations

TRIVIA_BANK: dict[str, list[str]] = {
    'What is 5 + 7?': ['12', 'twelve'],
    'What is 9 × 9?': ['81', 'eighty-one', 'eighty one'],
    'What is the square root of 144?': ['12', 'twelve'],
    'How many sides does a hexagon have?': ['6', 'six'],
    'What is 15% of 200?': ['30', 'thirty'],
    'What is 2 to the power of 8?': ['256'],
    'What is 7 × 8?': ['56', 'fifty-six', 'fifty six'],
    'How many degrees are in a right angle?': ['90', 'ninety'],
    'What is 100 divided by 4?': ['25', 'twenty-five', 'twenty five'],
    'What is the value of pi rounded to 2 decimal places?': ['3.14'],
    'What is the next prime number after 7?': ['11', 'eleven'],
    'What is 12 squared?': ['144'],
    'How many minutes are in 3 hours?': ['180'],
    'What is 1000 divided by 8?': ['125'],
    'What is 17 + 26?': ['43', 'forty-three', 'forty three'],
    'What gas do plants absorb from the air?': ['carbon dioxide', 'co2'],
    'What is H2O commonly known as?': ['water'],
    'How many bones are in the adult human body?': ['206'],
    'What planet is closest to the Sun?': ['mercury'],
    'What is the chemical symbol for gold?': ['au'],
    'What is the chemical symbol for iron?': ['fe'],
    'What force keeps us on the ground?': ['gravity'],
    'What is the speed of light (rounded) in km/s?': ['300000', '300,000'],
    'What organ pumps blood through the body?': ['heart'],
    'What is the powerhouse of the cell?': ['mitochondria'],
    'What gas do humans breathe out?': ['carbon dioxide', 'co2'],
    'How many chromosomes do humans have?': ['46'],
    'What is the hardest natural substance on Earth?': ['diamond'],
    'What planet is known as the Red Planet?': ['mars'],
    'What is the chemical symbol for water?': ['h2o'],
    'What is the capital of France?': ['paris'],
    'What is the capital of Japan?': ['tokyo'],
    'Which continent is Brazil on?': ['south america'],
    'What is the longest river in the world?': ['nile'],
    'What is the smallest country in the world?': ['vatican city', 'vatican'],
    'What is the tallest mountain in the world?': ['mount everest', 'everest'],
    'How many continents are there?': ['7', 'seven'],
    'What is the capital of Australia?': ['canberra'],
    'What ocean is the largest?': ['pacific', 'pacific ocean'],
    'What country has the most natural lakes?': ['canada'],
    'What is the capital of Canada?': ['ottawa'],
    'Which country is the Eiffel Tower in?': ['france'],
    'What is the capital of Germany?': ['berlin'],
    'What is the capital of Spain?': ['madrid'],
    'What river flows through Egypt?': ['nile', 'the nile'],
    'In what year did World War II end?': ['1945'],
    'Who was the first US President?': ['george washington', 'washington'],
    'What year did the Titanic sink?': ['1912'],
    'Which empire built the Colosseum?': ['roman', 'roman empire'],
    'In what year did the Berlin Wall fall?': ['1989'],
    'Who invented the telephone?': ['alexander graham bell', 'bell'],
    'What year did World War I begin?': ['1914'],
    'Who was the first person to walk on the Moon?': ['neil armstrong', 'armstrong'],
    'In what year did the French Revolution begin?': ['1789'],
    'Who wrote the Declaration of Independence?': ['thomas jefferson', 'jefferson'],
    'What game features a character named Master Chief?': ['halo'],
    'In Minecraft, what material is the strongest?': ['netherite'],
    "What is the name of Link's nemesis in Zelda?": ['ganon', 'ganondorf'],
    'What color is Pikachu?': ['yellow'],
    'What game has the Battle Bus?': ['fortnite'],
    'How many players start in a standard chess game?': ['32'],
    'What console did Nintendo release in 2017?': ['switch', 'nintendo switch'],
    'In Among Us, what are the killers called?': ['impostors', 'imposters', 'impostor'],
    'What is the max level in Minecraft?': ['2147483647'],
    "What game features 'Among Drip'?": ['among us'],
    "What is Roblox's virtual currency called?": ['robux'],
    'In Valorant, what is the objective bomb called?': ['spike'],
    'What year was Minecraft first released?': ['2009'],
    'How many players are in a standard League of Legends team?': ['5', 'five'],
    'What is the name of the currency in Animal Crossing?': ['bells'],
    "What does 'DM' stand for on Discord?": ['direct message'],
    "What does 'AFK' mean?": ['away from keyboard'],
    "What does 'GG' stand for in gaming?": ['good game'],
    "What does 'LFG' stand for?": ['looking for group'],
    "What does 'TBH' stand for?": ['to be honest'],
    "What color is Discord's logo?": ['purple', 'blurple'],
    "What does 'NGL' mean?": ['not gonna lie', 'not going to lie'],
    "What does 'POV' stand for?": ['point of view'],
    "What does 'FOMO' stand for?": ['fear of missing out'],
    "What does 'IRL' stand for?": ['in real life'],
    'How many planets are in our solar system?': ['8', 'eight'],
    'How many sides does a triangle have?': ['3', 'three'],
    'What color is the sky on a clear day?': ['blue'],
    'How many days are in a leap year?': ['366'],
    'What is the largest mammal in the world?': ['blue whale'],
    'How many strings does a standard guitar have?': ['6', 'six'],
    'What is the fastest land animal?': ['cheetah'],
    'How many colors are in a rainbow?': ['7', 'seven'],
    'What is the largest ocean on Earth?': ['pacific', 'pacific ocean'],
    'How many hours are in a day?': ['24', 'twenty-four'],
    'What language has the most native speakers?': ['mandarin', 'chinese', 'mandarin chinese'],
    'How many teeth do adult humans have?': ['32', 'thirty-two'],
    'What is the tallest animal on Earth?': ['giraffe'],
    'What is the currency of Japan?': ['yen'],
    'What is the currency of the UK?': ['pound', 'pounds', 'pound sterling'],
    'How many sides does a pentagon have?': ['5', 'five'],
    'What instrument has 88 keys?': ['piano'],
    'What is the largest planet in our solar system?': ['jupiter'],
    'Who painted the Mona Lisa?': ['leonardo da vinci', 'da vinci', 'leonardo'],
    'What is the national animal of Australia?': ['kangaroo'],
    'Who directed the movie Inception?': ['christopher nolan', 'nolan'],
    "What is the name of Tony Stark's AI assistant?": ['jarvis', 'j.a.r.v.i.s'],
    "In which film does the line 'I am your father' appear?": ['star wars', 'empire strikes back', 'the empire strikes back'],
    'What streaming service produced Stranger Things?': ['netflix'],
    'How many episodes are in the first season of Breaking Bad?': ['7', 'seven'],
    'What is the highest-grossing movie of all time?': ['avengers endgame', 'endgame'],
    "What movie features the song 'Let It Go'?": ['frozen'],
    "In Game of Thrones, what is the name of Jon Snow's direwolf?": ['ghost'],
    'How many players are on a basketball team on the court?': ['5', 'five'],
    'How many points is a touchdown worth in American football?': ['6', 'six'],
    'What country invented basketball?': ['usa', 'united states', 'america', 'united states of america'],
    'How many holes are in a standard round of golf?': ['18', 'eighteen'],
    'What is the diameter of a basketball hoop in inches?': ['18', 'eighteen'],
    'In tennis, what is a score of zero called?': ['love'],
    'How many rings does the Olympic logo have?': ['5', 'five'],
    'What sport is played at Wimbledon?': ['tennis'],
    'How many players are on a soccer team on the field?': ['11', 'eleven'],
    'What does CPU stand for?': ['central processing unit'],
    'What does RAM stand for?': ['random access memory'],
    "What is the most abundant gas in Earth's atmosphere?": ['nitrogen'],
    'What planet has the most moons?': ['saturn'],
    'How many bytes are in a kilobyte?': ['1024'],
    'What does HTML stand for?': ['hypertext markup language'],
    'What language is primarily used for web styling?': ['css'],
    'Who invented the World Wide Web?': ['tim berners-lee', 'berners-lee'],
    'What element has the atomic number 1?': ['hydrogen'],
    'What is the unit of electrical resistance?': ['ohm', 'ohms'],
    'How many seconds are in one hour?': ['3600'],
    'How many weeks are in a year?': ['52'],
    'What is the most spoken language in the world?': ['mandarin', 'chinese', 'mandarin chinese'],
    'What shape has 8 sides?': ['octagon'],
    'What is the square root of 256?': ['16', 'sixteen'],
    'How many zeros are in one million?': ['6', 'six'],
    'What is 17 × 17?': ['289'],
    'What is 25% of 400?': ['100'],
    'How many days are in September?': ['30', 'thirty'],
    'What is the Roman numeral for 100?': ['c'],
    'What is the chemical symbol for sodium?': ['na'],
    'What is the chemical symbol for oxygen?': ['o'],
    'What is the chemical symbol for potassium?': ['k'],
    'What is the freezing point of water in Celsius?': ['0', 'zero'],
    'What is the largest organ in the human body?': ['skin'],
    'How many legs does a spider have?': ['8', 'eight'],
    'What is the closest star to Earth?': ['the sun', 'sun'],
    'What is the study of living organisms called?': ['biology'],
    'What is the most abundant element in the universe?': ['hydrogen'],
    'What is the center of an atom called?': ['nucleus'],
    'What is the capital of Italy?': ['rome'],
    'What is the capital of Russia?': ['moscow'],
    'What is the capital of Egypt?': ['cairo'],
    'What is the capital of South Korea?': ['seoul'],
    'How many states are in the USA?': ['50', 'fifty'],
    'What is the capital of China?': ['beijing'],
    'What is the smallest continent?': ['australia', 'oceania'],
    'What is the capital of India?': ['new delhi', 'delhi'],
    'What is the largest country by land area?': ['russia'],
    'What is the tallest building in the world?': ['burj khalifa'],
    'Who was the British PM during most of WWII?': ['winston churchill', 'churchill'],
    'Who painted the ceiling of the Sistine Chapel?': ['michelangelo'],
    'In what year did humans first land on the Moon?': ['1969'],
    'What ancient civilization built the Giza pyramids?': ['egyptians', 'ancient egyptians', 'egypt'],
    'Who was the first man in space?': ['yuri gagarin', 'gagarin'],
    'What is the best-selling video game of all time?': ['minecraft'],
    'What company makes the PlayStation?': ['sony'],
    'What company makes the Xbox?': ['microsoft'],
    'What is the name of the princess in most Mario games?': ['peach', 'princess peach'],
    'What is the currency in Fortnite called?': ['v-bucks', 'vbucks', 'v bucks'],
    "In Tetris, how many lines at once make a 'Tetris'?": ['4', 'four'],
    'What does Mario usually stomp on?': ['goomba', 'goombas'],
    'How many players are in a standard Fortnite match?': ['100'],
    'How many keys are on a standard piano?': ['88'],
    "What does 'DJ' stand for?": ['disc jockey'],
    'How many musicians are in a quartet?': ['4', 'four'],
    'What is the highest female singing voice?': ['soprano'],
    'What fruit is used to make wine?': ['grapes', 'grape'],
    'What is the main ingredient in guacamole?': ['avocado', 'avocados'],
    'What spice is the most expensive by weight?': ['saffron'],
    'What beans are used to make chocolate?': ['cocoa', 'cacao', 'cocoa beans'],
    'What is the main ingredient in bread?': ['flour'],
    'What is 8 × 12?': ['96'],
    'What is half of 250?': ['125'],
    'What is 13 + 28?': ['41', 'forty-one', 'forty one'],
    'What is 6 × 6 × 6?': ['216'],
    'What is 9 × 6?': ['54', 'fifty-four', 'fifty four'],
    'How many colors are on a traffic light?': ['3', 'three'],
    'How many sides does a stop sign have?': ['8', 'eight'],
    'What is the freezing point of water in Fahrenheit?': ['32'],
    'How many millimeters are in a centimeter?': ['10', 'ten'],
    'How many legs does an insect have?': ['6', 'six'],
    'What is the only planet that rotates on its side?': ['uranus'],
    'What is the largest land animal?': ['elephant', 'african elephant'],
    'What is the chemical formula for table salt?': ['nacl'],
    'What is the chemical symbol for silver?': ['ag'],
    'What is the chemical symbol for helium?': ['he'],
    'What is the chemical symbol for carbon?': ['c'],
    'What planet is famous for its rings?': ['saturn'],
    'What is the boiling point of water in Fahrenheit?': ['212'],
    'What type of animal is a Komodo dragon?': ['lizard', 'reptile'],
    'What is the largest moon of Jupiter?': ['ganymede'],
    'What blood type is the universal donor?': ['o negative', 'o-'],
    'What vitamin does skin produce from sunlight?': ['vitamin d', 'd'],
    'What is the name of our galaxy?': ['milky way'],
    'What is the smallest unit of matter?': ['atom'],
    'What process do plants use to make food?': ['photosynthesis'],
    'How many teeth does an adult dog typically have?': ['42'],
    'What is the chemical symbol for lead?': ['pb'],
    'What is the most common blood type?': ['o positive', 'o+', 'o'],
    'What is the capital of Brazil?': ['brasilia'],
    'What is the capital of Greece?': ['athens'],
    'What is the capital of Portugal?': ['lisbon'],
    'What is the capital of Norway?': ['oslo'],
    'What is the largest hot desert in the world?': ['sahara'],
    'What country is shaped like a boot?': ['italy'],
    'On which continent is the Sahara Desert?': ['africa'],
    'What is the capital of Mexico?': ['mexico city'],
    'What is the longest mountain range in the world?': ['andes'],
    'What sea separates Europe and Africa?': ['mediterranean', 'mediterranean sea'],
    'What is the capital of Turkey?': ['ankara'],
    'What is the capital of Argentina?': ['buenos aires'],
    'Who was the first Emperor of Rome?': ['augustus'],
    'In what year did the American Civil War begin?': ['1861'],
    'Who is credited with reaching America in 1492?': ['christopher columbus', 'columbus'],
    'What wall divided a German city until 1989?': ['berlin wall', 'the berlin wall'],
    'Who was known as the Iron Lady?': ['margaret thatcher', 'thatcher'],
    'What ship did the Pilgrims sail to America?': ['mayflower', 'the mayflower'],
    'In what year did India gain independence?': ['1947'],
    "Who led India's nonviolent independence movement?": ['gandhi', 'mahatma gandhi'],
    'Which Egyptian queen was famously linked to Caesar?': ['cleopatra'],
    'Who played Jack in the film Titanic?': ['leonardo dicaprio', 'dicaprio', 'leo dicaprio'],
    'What is the name of the wizarding school in Harry Potter?': ['hogwarts'],
    "What fictional metal coats Wolverine's skeleton?": ['adamantium'],
    'Who is the green ogre in DreamWorks films?': ['shrek'],
    'In The Matrix, which pill does Neo take?': ['red', 'red pill'],
    "What is the name of Harry Potter's owl?": ['hedwig'],
    'Who directed Jurassic Park?': ['steven spielberg', 'spielberg'],
    'What superhero team includes Iron Man and Thor?': ['avengers', 'the avengers'],
    'Which band performed Bohemian Rhapsody?': ['queen'],
    "What was Beyonce's former girl group called?": ["destiny's child", 'destinys child'],
    'How many strings does a violin have?': ['4', 'four'],
    'Who is known as the King of Pop?': ['michael jackson'],
    'What genre is most associated with Bob Marley?': ['reggae'],
    'What country did pizza originate in?': ['italy'],
    'What is the main ingredient in hummus?': ['chickpeas', 'chickpea'],
    'What drink is made from fermented grapes?': ['wine'],
    'What nut is used to make marzipan?': ['almond', 'almonds'],
    'What is sushi traditionally wrapped in?': ['seaweed', 'nori'],
    'What fruit has its seeds on the outside?': ['strawberry', 'strawberries'],
    'What is the name of the hero in The Legend of Zelda?': ['link'],
    'What company developed Fortnite?': ['epic games', 'epic'],
    'In Mario Kart, what item makes you invincible?': ['star', 'super star'],
    "What is the name of Sega's blue hedgehog?": ['sonic'],
    'How many cards are in a standard deck?': ['52'],
    'In Minecraft, what mob explodes near players?': ['creeper'],
    'What does URL stand for?': ['uniform resource locator'],
    'What company created the iPhone?': ['apple'],
    'What does AI stand for?': ['artificial intelligence'],
    'What does USB stand for?': ['universal serial bus'],
    'What does GPU stand for?': ['graphics processing unit'],
    'What programming language shares its name with a snake?': ['python'],
    'What is the largest species of penguin?': ['emperor', 'emperor penguin'],
    'What is a baby kangaroo called?': ['joey'],
    'What is the only bird that can fly backwards?': ['hummingbird'],
    'What is the largest big cat?': ['tiger'],
    'How many hearts does an octopus have?': ['3', 'three'],
    'Which egg-laying mammal has a duck-like bill?': ['platypus'],
    'What is a group of lions called?': ['pride'],
    'Who wrote Romeo and Juliet?': ['shakespeare', 'william shakespeare'],
    'Who wrote the Harry Potter books?': ['j.k. rowling', 'jk rowling', 'rowling'],
    'In which novel does a whale named Moby Dick appear?': ['moby dick'],
    'Who wrote the novel 1984?': ['george orwell', 'orwell'],
    'What is the first book of the Bible?': ['genesis'],
    'Who created the detective Sherlock Holmes?': ['arthur conan doyle', 'conan doyle', 'doyle'],
    'How many sides does a dodecagon have?': ['12', 'twelve'],
    'What is the largest internal organ in the human body?': ['liver'],
    'How many planets in our solar system have rings?': ['4', 'four'],
    'What is the most consumed beverage after water?': ['tea'],
    'What color do you get mixing blue and yellow?': ['green'],
    'How many sides does a heptagon have?': ['7', 'seven'],
    'What is the chemical symbol for tin?': ['sn'],
    'How many degrees are in a full circle?': ['360'],
    'What is the currency of the United States?': ['dollar', 'us dollar', 'dollars'],
    'What gas makes up most of the Sun?': ['hydrogen'],
    'How many sides does a nonagon have?': ['9', 'nine'],
    'What is the tallest type of grass?': ['bamboo'],
    'What is the study of weather called?': ['meteorology'],
    'What metal is liquid at room temperature?': ['mercury'],
    'In which country would you find the Great Barrier Reef?': ['australia'],
    "Who wrote the play 'Romeo and Juliet'?": ['shakespeare', 'william shakespeare'],
    'How many continents are there on Earth?': ['7', 'seven'],
    'Which animal is known as the King of the Jungle?': ['lion'],
    'Which planet is closest to the Sun?': ['mercury'],
    'What is the smallest prime number?': ['2', 'two'],
    'What is the national language of Brazil?': ['portuguese'],
    'What gas do plants absorb from the atmosphere?': ['carbon dioxide', 'co2'],
    'Which is the longest river in the world?': ['nile', 'nile river'],
    'Who is the Greek god of the sea?': ['poseidon'],
    'How many players from one soccer team are on the field?': ['11', 'eleven'],
    'Which country gifted the Statue of Liberty to the USA?': ['france'],
    'How many colors are there in a rainbow?': ['7', 'seven'],
    'Who formulated the law of gravity after an apple fell?': ['newton', 'isaac newton'],
}

SCRAMBLE_WORDS: list = [
    'python',
    'discord',
    'server',
    'economy',
    'lootbox',
    'scramble',
    'trivia',
    'reward',
    'points',
    'channel',
    'button',
    'winner',
    'random',
    'treasure',
    'typing',
    'keyboard',
    'monitor',
    'laptop',
    'internet',
    'browser',
    'network',
    'router',
    'firewall',
    'bandwidth',
    'streaming',
    'database',
    'command',
    'message',
    'reaction',
    'webhook',
    'sidebar',
    'mention',
    'profile',
    'nickname',
    'fortnite',
    'minecraft',
    'roblox',
    'valorant',
    'overwatch',
    'pokemon',
    'dungeon',
    'dragon',
    'warrior',
    'potion',
    'respawn',
    'loadout',
    'headshot',
    'camping',
    'airdrop',
    'sniper',
]

EMOJI_PUZZLES: list[tuple[str, str]] = [
    ('🦁👑', 'The Lion King'),
    ('🕷️🧑', 'Spider-Man'),
    ('🧊❄️👸', 'Frozen'),
    ('🤠🐍🌀', 'Indiana Jones'),
    ('🦈🌊😱', 'Jaws'),
    ('🌌⭐🚀', 'Star Wars'),
    ('🤖🚗🔁', 'Transformers'),
    ('🧙💍🔥', 'Lord of the Rings'),
    ('🦋🦅🤿', 'Avatar'),
    ('👻🏚️🕯️', 'Ghostbusters'),
    ('🦸\u200d♂️���🌃', 'Batman'),
    ('🏎️💨⚡', 'Cars'),
    ('🧟🌍💀', 'World War Z'),
    ('🐠🌊🐟', 'Finding Nemo'),
    ('🐀🍳👨\u200d🍳', 'Ratatouille'),
    ('👶🤖❤️', 'A.I. Artificial Intelligence'),
    ('🧸🎠🌈', 'Toy Story'),
    ('🐼🥋🐉', 'Kung Fu Panda'),
    ('🕰️✈️🧒', 'Peter Pan'),
    ('🌕🧑\u200d🚀🌑', 'Apollo 13'),
    ('🧪🔵💎', 'Breaking Bad'),
    ('🐉🏰🗡️', 'Game of Thrones'),
    ('🏝️🌴✈️💥', 'Lost'),
    ('🌂☂️💛💙', 'How I Met Your Mother'),
    ('🏥💊🩺', "Grey's Anatomy"),
    ('🕵️🔍🧠', 'Sherlock'),
    ('👨\u200d💼📊💰', 'The Office'),
    ('🌵🤠🔫', 'Breaking Bad'),
    ('🤝😊📋', 'Friends'),
    ('🧟🌆🔫', 'The Walking Dead'),
    ('🚂⌚🌌', 'Dark'),
    ('🤵🍸🎰', 'Suits'),
    ('🧹🔮📚', 'The Witcher'),
    ('👩\u200d🔬🧬🔭', 'Stranger Things'),
    ('🏫🪄🦉', 'Harry Potter'),
    ('🍄👷🏰', 'Super Mario'),
    ('🧱💎⛏️', 'Minecraft'),
    ('🌀🦔💨', 'Sonic the Hedgehog'),
    ('⚔️🛡️🧝', 'The Legend of Zelda'),
    ('🔴🟡🟢⬆️', 'Among Us'),
    ('🦆🎮🏆', 'Duck Hunt'),
    ('🃏🎯🔫', 'Valorant'),
    ('🤖🌍⚙️', 'Horizon Zero Dawn'),
    ('🐉🌐🗡️', 'World of Warcraft'),
    ('🔫🏝️🪂', 'PUBG'),
    ('👁️🌑👾', 'Dead Space'),
    ('🏙️🚗💥', 'Grand Theft Auto'),
    ('🦸\u200d♂️🦹\u200d♂️🏙️', "Marvel's Spider-Man"),
    ('🌊🤿🐠🏝️', 'Subnautica'),
    ('🪐🚀🌌', 'Mass Effect'),
]

FILL_BLANK_BANK: list[dict] = [
    {'prompt': "Fill in the blank: 'To be or not to be, that is the ___'", 'answer': ['question']},
    {'prompt': "Fill in the blank: 'The early bird catches the ___'", 'answer': ['worm']},
    {'prompt': "Fill in the blank: 'Rome wasn't built in a ___'", 'answer': ['day']},
    {'prompt': "Fill in the blank: 'Actions speak louder than ___'", 'answer': ['words']},
    {'prompt': "Fill in the blank: 'Every cloud has a silver ___'", 'answer': ['lining']},
    {'prompt': "Fill in the blank: 'You can't judge a book by its ___'", 'answer': ['cover']},
    {'prompt': "Fill in the blank: 'The pen is mightier than the ___'", 'answer': ['sword']},
    {'prompt': "Fill in the blank: 'Practice makes ___'", 'answer': ['perfect']},
    {'prompt': "Fill in the blank: 'Better late than ___'", 'answer': ['never']},
    {'prompt': "Fill in the blank: 'Two wrongs don't make a ___'", 'answer': ['right']},
    {'prompt': "Fill in the blank: 'Where there's smoke, there's ___'", 'answer': ['fire']},
    {'prompt': "Fill in the blank: 'The squeaky wheel gets the ___'", 'answer': ['grease']},
    {'prompt': "Fill in the blank: 'Don't count your chickens before they ___'", 'answer': ['hatch']},
    {'prompt': "Fill in the blank: 'A penny saved is a penny ___'", 'answer': ['earned']},
    {'prompt': "Fill in the blank: 'The grass is always greener on the other ___'", 'answer': ['side']},
    {'prompt': "Fill in the blank: 'Curiosity killed the ___'", 'answer': ['cat']},
    {'prompt': "Fill in the blank: 'A picture is worth a thousand ___'", 'answer': ['words']},
    {'prompt': "Fill in the blank: 'Don't bite the hand that ___  you'", 'answer': ['feeds']},
    {'prompt': "Fill in the blank: 'All that glitters is not ___'", 'answer': ['gold']},
    {'prompt': "Fill in the blank: 'Beggars can't be ___'", 'answer': ['choosers']},
    {'prompt': "Fill in the blank: 'The best things in life are ___'", 'answer': ['free']},
    {'prompt': "Fill in the blank: 'No pain, no ___'", 'answer': ['gain']},
    {'prompt': "Fill in the blank: 'You reap what you ___'", 'answer': ['sow']},
    {'prompt': "Fill in the blank: 'Keep your friends close, and your enemies ___'", 'answer': ['closer']},
    {'prompt': "Fill in the blank: 'There's no place like ___'", 'answer': ['home']},
    {'prompt': "Fill in the blank: 'Slow and steady wins the ___'", 'answer': ['race']},
    {'prompt': "Fill in the blank: 'When in Rome, do as the Romans ___'", 'answer': ['do']},
    {'prompt': "Fill in the blank: 'You can lead a horse to water but you can't make it ___'", 'answer': ['drink']},
    {'prompt': "Fill in the blank: 'An apple a day keeps the ___ away'", 'answer': ['doctor']},
    {'prompt': "Fill in the blank: 'The ___ always rings twice' (1946 film)", 'answer': ['postman']},
    {'prompt': "Fill in the blank: 'May the ___ be with you' (Star Wars)", 'answer': ['force']},
    {'prompt': "Fill in the blank: 'To infinity and ___' (Toy Story)", 'answer': ['beyond']},
    {'prompt': "Fill in the blank: 'Just keep ___' (Finding Nemo)", 'answer': ['swimming']},
    {'prompt': "Fill in the blank: 'With great power comes great ___'", 'answer': ['responsibility']},
    {'prompt': "Fill in the blank: 'I'll be ___' (Terminator)", 'answer': ['back']},
    {'prompt': "Fill in the blank: 'Better safe than ___'", 'answer': ['sorry']},
    {'prompt': "Fill in the blank: 'Honesty is the best ___'", 'answer': ['policy']},
    {'prompt': "Fill in the blank: 'Birds of a feather flock ___'", 'answer': ['together']},
    {'prompt': "Fill in the blank: 'A friend in need is a friend ___'", 'answer': ['indeed']},
    {'prompt': "Fill in the blank: 'Out of sight, out of ___'", 'answer': ['mind']},
    {'prompt': "Fill in the blank: 'Easy come, easy ___'", 'answer': ['go']},
    {'prompt': "Fill in the blank: 'Laughter is the best ___'", 'answer': ['medicine']},
    {'prompt': "Fill in the blank: 'Time is ___'", 'answer': ['money']},
    {'prompt': "Fill in the blank: 'Knowledge is ___'", 'answer': ['power']},
    {'prompt': "Fill in the blank: 'Home is where the ___ is'", 'answer': ['heart']},
    {'prompt': "Fill in the blank: 'Live and let ___'", 'answer': ['live']},
    {'prompt': "Fill in the blank: 'When the going gets tough, the tough get ___'", 'answer': ['going']},
    {'prompt': "Fill in the blank: 'Necessity is the mother of ___'", 'answer': ['invention']},
    {'prompt': "Fill in the blank: 'The apple doesn't fall far from the ___'", 'answer': ['tree']},
    {'prompt': "Fill in the blank: 'A watched pot never ___'", 'answer': ['boils']},
]

MATH_BANK: list[dict] = [
    {'prompt': '⚡ Fast Math: What is 13 × 13?', 'answer': ['169']},
    {'prompt': '⚡ Fast Math: What is 17 × 8?', 'answer': ['136']},
    {'prompt': '⚡ Fast Math: What is 225 ÷ 15?', 'answer': ['15']},
    {'prompt': '⚡ Fast Math: What is 12 × 14?', 'answer': ['168']},
    {'prompt': '⚡ Fast Math: What is 48 × 3?', 'answer': ['144']},
    {'prompt': '⚡ Fast Math: What is 19 × 7?', 'answer': ['133']},
    {'prompt': '⚡ Fast Math: What is 360 ÷ 12?', 'answer': ['30']},
    {'prompt': '⚡ Fast Math: What is 16 × 16?', 'answer': ['256']},
    {'prompt': '⚡ Fast Math: What is 3 + 7 × 4?', 'answer': ['31']},
    {'prompt': '⚡ Fast Math: What is (12 + 8) × 5?', 'answer': ['100']},
    {'prompt': '⚡ Fast Math: What is 100 − 37 + 12?', 'answer': ['75']},
    {'prompt': '⚡ Fast Math: What is 9² + 9?', 'answer': ['90']},
    {'prompt': '⚡ Fast Math: What is 500 ÷ 4?', 'answer': ['125']},
    {'prompt': '⚡ Fast Math: What is 25 × 8?', 'answer': ['200']},
    {'prompt': '⚡ Fast Math: What is 11 × 11 − 1?', 'answer': ['120']},
    {'prompt': '⚡ Fast Math: What is 72 ÷ 8 × 6?', 'answer': ['54']},
    {'prompt': '⚡ Fast Math: What is 15² − 100?', 'answer': ['125']},
    {'prompt': '⚡ Fast Math: What is 1000 − 237?', 'answer': ['763']},
    {'prompt': '⚡ Fast Math: What is 6 × 7 × 2?', 'answer': ['84']},
    {'prompt': '⚡ Fast Math: What is 144 ÷ 12 + 8?', 'answer': ['20']},
    {'prompt': '⚡ Fast Math: What is 50% of 360?', 'answer': ['180']},
    {'prompt': '⚡ Fast Math: What is 20% of 250?', 'answer': ['50']},
    {'prompt': '⚡ Fast Math: What is 3³?', 'answer': ['27']},
    {'prompt': '⚡ Fast Math: What is 4⁴?', 'answer': ['256']},
    {'prompt': '⚡ Fast Math: What is 7 × 7 × 7?', 'answer': ['343']},
    {'prompt': '⚡ Fast Math: What is (100 ÷ 5) × 7?', 'answer': ['140']},
    {'prompt': '⚡ Fast Math: What is 999 + 111?', 'answer': ['1110']},
    {'prompt': '⚡ Fast Math: What is 18 × 18?', 'answer': ['324']},
    {'prompt': '⚡ Fast Math: What is 2⁸?', 'answer': ['256']},
    {'prompt': '⚡ Fast Math: What is 1000 ÷ 8?', 'answer': ['125']},
    {'prompt': '⚡ Fast Math: What is 14 × 5?', 'answer': ['70']},
    {'prompt': '⚡ Fast Math: What is 21 × 3?', 'answer': ['63']},
    {'prompt': '⚡ Fast Math: What is 256 ÷ 8?', 'answer': ['32']},
    {'prompt': '⚡ Fast Math: What is 45 + 67?', 'answer': ['112']},
    {'prompt': '⚡ Fast Math: What is 90 ÷ 6 × 4?', 'answer': ['60']},
    {'prompt': '⚡ Fast Math: What is 13²?', 'answer': ['169']},
    {'prompt': '⚡ Fast Math: What is 7 × 9 + 7?', 'answer': ['70']},
    {'prompt': '⚡ Fast Math: What is 800 − 256?', 'answer': ['544']},
    {'prompt': '⚡ Fast Math: What is 30% of 90?', 'answer': ['27']},
    {'prompt': '⚡ Fast Math: What is 5! (factorial)?', 'answer': ['120']},
    {'prompt': '⚡ Fast Math: What is 12 × 12?', 'answer': ['144']},
    {'prompt': '⚡ Fast Math: What is 12 × 13?', 'answer': ['156']},
    {'prompt': '⚡ Fast Math: What is 12 × 15?', 'answer': ['180']},
    {'prompt': '⚡ Fast Math: What is 12 × 16?', 'answer': ['192']},
    {'prompt': '⚡ Fast Math: What is 12 × 17?', 'answer': ['204']},
    {'prompt': '⚡ Fast Math: What is 12 × 18?', 'answer': ['216']},
    {'prompt': '⚡ Fast Math: What is 12 × 19?', 'answer': ['228']},
    {'prompt': '⚡ Fast Math: What is 12 × 20?', 'answer': ['240']},
    {'prompt': '⚡ Fast Math: What is 12 × 21?', 'answer': ['252']},
    {'prompt': '⚡ Fast Math: What is 13 × 12?', 'answer': ['156']},
]

TRUE_FALSE_BANK: list[dict] = [
    {'statement': 'The Great Wall of China is visible from space with the naked eye.', 'answer': False, 'fact': "This is a myth — it's too narrow to be seen from orbit."},
    {'statement': 'Humans share about 60% of their DNA with bananas.', 'answer': True, 'fact': 'We share roughly 60% of our DNA with bananas.'},
    {'statement': 'Lightning never strikes the same place twice.', 'answer': False, 'fact': 'Lightning can and does strike the same place multiple times.'},
    {'statement': 'Goldfish have a memory span of only 3 seconds.', 'answer': False, 'fact': 'Goldfish can remember things for months.'},
    {'statement': 'The Eiffel Tower grows taller in summer due to heat expansion.', 'answer': True, 'fact': 'It can grow up to 15 cm taller in hot weather.'},
    {'statement': 'Bats are blind.', 'answer': False, 'fact': 'Bats have functional eyes and can see — they also use echolocation.'},
    {'statement': 'An octopus has three hearts.', 'answer': True, 'fact': 'Octopuses have two branchial hearts and one systemic heart.'},
    {'statement': 'Water boils at 100°C at sea level.', 'answer': True, 'fact': 'Water boils at 100°C (212°F) at standard sea-level pressure.'},
    {'statement': 'The Amazon River is the longest river in the world.', 'answer': False, 'fact': 'The Nile is generally considered the longest river.'},
    {'statement': 'Venus is the hottest planet in our solar system.', 'answer': True, 'fact': 'Venus is hotter than Mercury due to its thick greenhouse atmosphere.'},
    {'statement': 'A group of flamingos is called a flamboyance.', 'answer': True, 'fact': 'Yes — a flamboyance of flamingos!'},
    {'statement': 'Diamonds are made of carbon.', 'answer': True, 'fact': 'Diamonds are pure crystallized carbon.'},
    {'statement': 'Sharks are mammals.', 'answer': False, 'fact': 'Sharks are fish, not mammals.'},
    {'statement': 'Sound travels faster than light.', 'answer': False, 'fact': 'Light travels at ~300,000 km/s; sound at ~343 m/s.'},
    {'statement': 'Napoleon Bonaparte was unusually short for his era.', 'answer': False, 'fact': 'He was about 5\'7" — average height for his time.'},
    {'statement': 'Humans use only 10% of their brain.', 'answer': False, 'fact': 'Brain scans show we use virtually all of our brain.'},
    {'statement': 'A group of cats is called a clowder.', 'answer': True, 'fact': 'A clowder is the correct term for a group of cats.'},
    {'statement': 'The sun is a star.', 'answer': True, 'fact': 'The sun is a G-type main-sequence star.'},
    {'statement': 'Snakes have eyelids.', 'answer': False, 'fact': 'Snakes have a clear scale over their eyes, not eyelids.'},
    {'statement': 'The tongue is the strongest muscle in the human body.', 'answer': False, 'fact': 'The masseter (jaw muscle) is considered the strongest.'},
    {'statement': "Elephants are the only animals that can't jump.", 'answer': False, 'fact': "Several other animals can't jump either (hippos, rhinos, etc.)."},
    {'statement': "A duck's quack does not echo.", 'answer': False, 'fact': "A duck's quack does echo — this is a myth."},
    {'statement': 'The Pacific Ocean is larger than all land on Earth combined.', 'answer': True, 'fact': 'The Pacific Ocean covers more area than all land masses combined.'},
    {'statement': 'Honey never expires.', 'answer': True, 'fact': 'Honey found in ancient Egyptian tombs was still edible.'},
    {'statement': 'A day on Venus is longer than a year on Venus.', 'answer': True, 'fact': 'Venus rotates so slowly its day is longer than its orbit around the Sun.'},
    {'statement': 'Mount Everest is the tallest mountain above sea level.', 'answer': True, 'fact': 'Everest stands about 8,849 m above sea level.'},
    {'statement': 'Tomatoes are vegetables, not fruits.', 'answer': False, 'fact': 'Botanically, tomatoes are fruits.'},
    {'statement': 'Humans have two lungs.', 'answer': True, 'fact': 'Humans have a left and right lung.'},
    {'statement': 'Spiders are insects.', 'answer': False, 'fact': 'Spiders are arachnids, not insects.'},
    {'statement': 'Penguins can fly.', 'answer': False, 'fact': 'Penguins are flightless birds; they swim instead.'},
    {'statement': 'Mercury is the closest planet to the Sun.', 'answer': True, 'fact': 'Mercury orbits closest to the Sun.'},
    {'statement': 'Bananas grow on trees.', 'answer': False, 'fact': 'Banana plants are giant herbs, not trees.'},
    {'statement': 'Gold is denser than iron.', 'answer': True, 'fact': 'Gold is denser and heavier than iron by volume.'},
    {'statement': 'Owls can rotate their heads a full 360 degrees.', 'answer': False, 'fact': 'Owls rotate their heads about 270 degrees.'},
    {'statement': 'The Sun appears to rise in the east.', 'answer': True, 'fact': "Earth's rotation makes the Sun appear to rise in the east."},
    {'statement': 'There are 100 minutes in an hour.', 'answer': False, 'fact': 'There are 60 minutes in an hour.'},
    {'statement': "A shrimp's heart is located in its head.", 'answer': True, 'fact': "A shrimp's heart is in its head region."},
    {'statement': 'Bananas are berries, botanically speaking.', 'answer': True, 'fact': 'Botanically, bananas qualify as berries.'},
    {'statement': 'Strawberries are true berries, botanically.', 'answer': False, 'fact': 'Strawberries are not true berries botanically.'},
    {'statement': 'The human heart has four chambers.', 'answer': True, 'fact': 'Two atria and two ventricles.'},
    {'statement': 'Sound cannot travel through the vacuum of space.', 'answer': True, 'fact': 'Space is a vacuum, so sound cannot travel.'},
    {'statement': 'The Sun is mostly made of helium.', 'answer': False, 'fact': 'The Sun is mostly hydrogen.'},
    {'statement': 'Mount Kilimanjaro is located in Africa.', 'answer': True, 'fact': 'It is in Tanzania.'},
    {'statement': 'Sharks existed before trees did.', 'answer': True, 'fact': 'Sharks predate trees by millions of years.'},
    {'statement': 'A jiffy is an actual unit of time.', 'answer': True, 'fact': 'A jiffy is a real measure of time in physics.'},
    {'statement': 'Glass is a slow-moving liquid at room temperature.', 'answer': False, 'fact': 'Glass is an amorphous solid, not a liquid.'},
    {'statement': 'The Eiffel Tower was originally meant to be temporary.', 'answer': True, 'fact': "It was built for the 1889 World's Fair."},
    {'statement': 'Octopuses have blue blood.', 'answer': True, 'fact': 'Their blood is copper-based (hemocyanin).'},
    {'statement': 'The shortest war in history lasted under an hour.', 'answer': True, 'fact': 'The Anglo-Zanzibar War lasted about 38 minutes.'},
    {'statement': 'Polar bears have white skin under their fur.', 'answer': False, 'fact': 'Polar bears have black skin under clear fur.'},
]
