"""Random 'requirement to leave jail' messages posted when someone is jailed."""

JAIL_REQUIREMENTS: tuple[str, ...] = (
    "Send a 15-word apology to oxygen for wasting it to leave this jail.",
    "Say the following oath: I hereby agree to stop being horny, stick to my morals and ethics, and be a reformed member of society.",
    "Type **I will not act up again** three times, each on its own line, then wait out your sentence.",
    "Write a haiku about personal growth. Syllables optional. Freedom is not optional.",
    "Confess one thing you did wrong today in exactly 20 words — no more, no less.",
    "Address the jail as **Your Honor** in your next message and ask politely for parole.",
    "Explain why your behavior was unacceptable using only emojis. Minimum ten emojis.",
    "Recite the alphabet backwards from Z to A without googling it. Typos forgiven.",
    "Apologize to the nearest plant, screenshot your sincerity, and describe the plant's reaction.",
    "Write **I am the problem** five times with increasing dramatic capitalization.",
    "Compose a two-sentence breakup letter to your worst habit.",
    "List three ways you will be a better person. Bullet points only. No cop-outs.",
    "Say **touch grass** and mean it spiritually for the remainder of your sentence.",
    "Invent a new rule for this server that you personally will follow forever.",
    "Write a sincere thank-you note to the mod who jailed you. Flattery won't shorten time.",
    "Describe your actions using only movie titles separated by commas.",
    "Type **my bad** in five different languages. Google Translate is allowed. Growth is mandatory.",
    "Create a motivational quote as if you are a reformed villain giving a TED Talk.",
    "Admit one embarrassing truth about yourself. The jail respects honesty.",
    "Write a 30-word essay titled **Why I Deserved This** without using the word 'unfair'.",
    "Perform a virtual bow by typing `( bows )` and promise to do better.",
    "Name three things you will stop doing in chat. Be specific or stay jailed longer in spirit.",
    "Write an apology rap. Minimum four lines. Bars optional; remorse required.",
    "Type **I have learned my lesson** and then explain what the lesson actually was.",
    "Summarize your offense in one sentence starting with **Honestly...**",
    "Pledge allegiance to good vibes only for the next seven days.",
    "Write a breakup text to drama. Make it final.",
    "Confess whether you knew better. Spoiler: you did.",
    "List five synonyms for **accountability** and use one in a sentence about yourself.",
    "Say **I will read the rules** and name one rule you broke.",
    "Compose a short prayer to the moderation gods. Keep it respectful.",
    "Type **I am cooked** and explain how you got yourself cooked.",
    "Write a fake news headline about your reformation. Make it believable.",
    "Apologize to everyone in this channel by @ mentioning nobody and taking full blame anyway.",
    "Describe your personality before and after this jail arc in two sentences each.",
    "Say **I will touch grass IRL** and describe what grass you will touch.",
    "Write a contract with yourself. Include one clause about not being chaotic.",
    "Rank your decision-making today from 1 to 10. Defend the score.",
    "Type **sigma grindset cancelled** and propose a healthier grindset.",
    "Explain your behavior to a hypothetical five-year-old. Keep it PG.",
    "Write **dear diary** followed by one paragraph of genuine self-reflection.",
    "Name the mod you disappointed and say sorry without making excuses.",
    "List three coping mechanisms that are not starting drama in chat.",
    "Say **I will log off when angry** and mean it for at least 24 hours after release.",
    "Write a Yelp review of this jail. Five stars for accountability.",
    "Type **no cap** and then tell the truth with your whole chest.",
    "Invent a superhero named **Reformed You** and describe their powers.",
    "Apologize to the concept of **decency** like it can hear you.",
    "Write one thing you will do differently tomorrow. Be concrete.",
    "Say **I have humbly accepted my L** and describe the L.",
    "Compose a fortune-cookie message you'd give your past self before you acted up.",
    "Type **respectfully** before every sentence in your next message here. All of them.",
    "Write a cease-and-desist letter to your own bad takes.",
    "Explain why mods are not your enemies in under 40 words.",
    "Say **I will think before I type** ten times fast without typos.",
    "Draft a public service announcement warning others not to do what you did.",
    "Write **I am not the main character** and explain who actually is.",
    "Apologize to silence for filling it with nonsense.",
    "List your top three triggers for bad behavior and how you'll avoid them.",
    "Type **lesson learned** backwards. Then forwards. Then live it.",
    "Write a breakup letter to impulsive messaging.",
    "Say **I will use my brain** and provide evidence you own one.",
    "Confess the moment you knew you messed up. Be precise.",
    "Write a short ode to consequences. Rhyme optional; acceptance mandatory.",
    "Pledge to drink water, touch grass, and stop being unhinged in general chat.",
)
